import { createRouter, createWebHashHistory } from 'vue-router'

const routes = [
  { path: '/login', name: 'Login', component: () => import('../views/LoginView.vue') },
  { path: '/userInfo', name: 'UserInfo', component: () => import('../views/UserInfoView.vue') },
  { path: '/pay', name: 'Pay', component: () => import('../views/PayView.vue') },
  { path: '/wxlogin', name: 'WxLogin', component: () => import('../views/WxLoginView.vue') },
  { path: '/', name: 'Update', component: () => import('../views/UpdateView.vue') },
  { path: '/home', name: 'Home', component: () => import('../views/HomeView.vue') },
  { path: '/book', name: 'Book', component: () => import('../views/ReaderView.vue'), meta: { mode: 'float' } },
  { path: '/bookReader', name: 'BookReader', component: () => import('../views/ReaderView.vue'), meta: { mode: 'shelf' } },
  { path: '/bookReaderOpacity', name: 'BookReaderOpacity', component: () => import('../views/ReaderView.vue'), meta: { mode: 'opacity' } },
  { path: '/readView', name: 'ReadView', component: () => import('../views/ReaderView.vue'), meta: { mode: 'read' } },
  { path: '/bookReaderAd', name: 'BookReaderAd', component: () => import('../views/ReaderView.vue'), meta: { mode: 'ad' } },
  { path: '/web', name: 'Web', component: () => import('../views/SiteView.vue'), meta: { site: 'web' } },
  { path: '/testPierce', name: 'TestPierce', component: () => import('../views/TestPierceView.vue') },
  { path: '/customWebpage', name: 'CustomWebpage', component: () => import('../views/CustomWebpageView.vue') },
  { path: '/douyin', name: 'Douyin', component: () => import('../views/VideoAdView.vue'), meta: { site: 'douyin', mode: 'ad' } },
  { path: '/douyinOpacity', name: 'DouyinOpacity', component: () => import('../views/DouyinOpacityView.vue'), meta: { site: 'douyin', mode: 'opacity' } },
  { path: '/kuaishou', name: 'Kuaishou', component: () => import('../views/VideoAdView.vue'), meta: { site: 'kuaishou', mode: 'ad' } },
  { path: '/kuaishouOpacity', name: 'KuaishouOpacity', component: () => import('../views/VideoOpacityView.vue'), meta: { site: 'kuaishou', mode: 'opacity' } },
  { path: '/weRead', name: 'WeRead', component: () => import('../views/WeReadView.vue'), meta: { site: 'weRead' } },
  { path: '/weReadAd', name: 'WeReadAd', component: () => import('../views/ReadingAdView.vue'), meta: { site: 'weRead', mode: 'ad' } },
  { path: '/weReadAdOld', name: 'WeReadAdOld', component: () => import('../views/SiteView.vue'), meta: { site: 'weRead', mode: 'adOld' } },
  { path: '/customWebsiteAd', name: 'CustomWebsiteAd', component: () => import('../views/SiteView.vue'), meta: { site: 'custom', mode: 'ad', custom: true } },
  { path: '/customWebsiteOpacity', name: 'CustomWebsiteOpacity', component: () => import('../views/SiteView.vue'), meta: { site: 'custom', mode: 'opacity', custom: true } },
  { path: '/standaloneGameAd', name: 'StandaloneGameAd', component: () => import('../views/SiteView.vue'), meta: { site: 'game', mode: 'ad' } },
  { path: '/standaloneGameOpacity', name: 'StandaloneGameOpacity', component: () => import('../views/SiteView.vue'), meta: { site: 'game', mode: 'opacity' } },
  { path: '/zhihu', name: 'Zhihu', component: () => import('../views/SiteView.vue'), meta: { site: 'zhihu' } },
  { path: '/fanQue', name: 'FanQue', component: () => import('../views/ReadingSiteView.vue'), meta: { site: 'fanQue' } },
  { path: '/jinJiang', name: 'JinJiang', component: () => import('../views/ReadingSiteView.vue'), meta: { site: 'jinJiang' } },
  { path: '/bilibili', name: 'Bilibili', component: () => import('../views/VideoAdView.vue'), meta: { site: 'bilibili', mode: 'ad' } },
  { path: '/bilibiliOpacity', name: 'BilibiliOpacity', component: () => import('../views/VideoOpacityView.vue'), meta: { site: 'bilibili', mode: 'opacity' } },
  { path: '/excel', name: 'Excel', component: () => import('../views/ExcelView.vue') },
  { path: '/excel-view', name: 'ExcelView', component: () => import('../views/ExcelView.vue'), meta: { mode: 'view' } },
  { path: '/keyword', name: 'Keyword', component: () => import('../views/KeywordView.vue') },
  { path: '/wechat', name: 'Wechat', component: () => import('../views/WechatView.vue'), meta: { kind: 'wechat' } },
  { path: '/wechatConfig', name: 'WechatConfig', component: () => import('../views/ChatConfigView.vue'), meta: { kind: 'wechat' } },
  { path: '/dingding', name: 'Dingding', component: () => import('../views/DingTalkView.vue'), meta: { kind: 'dingding' } },
  { path: '/dingdingConfig', name: 'DingdingConfig', component: () => import('../views/ChatConfigView.vue'), meta: { kind: 'dingding' } },
  { path: '/feishu', name: 'Feishu', component: () => import('../views/FeishuView.vue'), meta: { kind: 'feishu' } },
  { path: '/huyaOpacity', name: 'HuyaOpacity', component: () => import('../views/VideoOpacityView.vue'), meta: { site: 'huya', mode: 'opacity' } },
  { path: '/huya', name: 'Huya', component: () => import('../views/VideoAdView.vue'), meta: { site: 'huya', mode: 'ad' } },
  { path: '/huyaControl', name: 'HuyaControl', component: () => import('../views/ControlView.vue'), meta: { kind: 'huya' } },
  { path: '/douyuControl', name: 'DouyuControl', component: () => import('../views/ControlView.vue'), meta: { kind: 'douyu' } },
  { path: '/douyuOpacity', name: 'DouyuOpacity', component: () => import('../views/SiteView.vue'), meta: { site: 'douyu', mode: 'opacity' } },
  { path: '/douyu', name: 'Douyu', component: () => import('../views/VideoAdView.vue'), meta: { site: 'douyu', mode: 'ad' } },
  { path: '/localVideo', name: 'LocalVideo', component: () => import('../views/VideoView.vue') },
  { path: '/localVideoOpacity', name: 'LocalVideoOpacity', component: () => import('../views/VideoView.vue'), meta: { mode: 'opacity' } }
]

export default createRouter({
  history: createWebHashHistory(),
  routes
})
