const {app,BrowserWindow,session,webContents,globalShortcut}=require('electron')
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict')
if(!process.env.MOYU_CHAT_DATA_DIR)throw Error('Isolated chat data required')
app.setPath('userData',process.env.MOYU_CHAT_DATA_DIR);app.disableHardwareAcceleration()
const pause=ms=>new Promise(r=>setTimeout(r,ms)),evaluate=(w,code)=>w.webContents.executeJavaScript(`(()=>{return eval(${JSON.stringify(code)})})()`,true)
const find=route=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('#'+route))
let passed=0;const errors=[]
app.on('web-contents-created',(_e,wc)=>wc.on('console-message',(_e,level,message)=>{if(level>=3&&!message.includes('favicon'))errors.push(message)}))
async function until(fn,label,attempts=80){for(let i=0;i<attempts;i++){if(await fn())return;await pause(100)}throw Error('Timeout: '+label)}
async function check(name,fn){await fn();passed++;console.log('PASS '+name)}
const click=(w,a)=>evaluate(w,`document.querySelector('[data-action="${a}"]').click()`)
const ready=w=>until(()=>evaluate(w,"document.querySelector('[data-chat-ready]')?.dataset.chatReady==='true'"),'new formal WeChat ready')
const input=(w,key,v)=>evaluate(w,`(()=>{const i=document.querySelector('[data-setting="${key}"]');i.value=${JSON.stringify(v)};i.dispatchEvent(new Event('change',{bubbles:true}))})()`)
const watchdog=setTimeout(()=>{console.error('Chat smoke watchdog');app.exit(1)},60000)
app.whenReady().then(async()=>{
  let html=fs.readFileSync(path.join(__dirname,'../tests/fixtures/web/ad-modes/video.html'),'utf8')
  html=html.replace('</body>','</body>')+'<script>document.addEventListener("wheel",()=>document.body.dataset.wheel="yes");</script>'
  await session.fromPartition('persist:moyu-chat-wechat').protocol.handle('https',async request=>{
    const pathname=new URL(request.url).pathname
    if(pathname==='/video/slowA')await pause(800)
    if(pathname==='/redirect-block')return new Response(null,{status:302,headers:{Location:'https://blocked.invalid/'}})
    if(pathname==='/redirect-insite')return new Response(null,{status:302,headers:{Location:'https://www.douyin.com/video/canonical'}})
    return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8'}})
  })
  await session.defaultSession.protocol.handle('https',()=>new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8'}}))
  try{
    await until(()=>find('/home'),'home');const home=find('/home')
    await evaluate(home,"window.homeElectronAPI.createWechat()");await until(()=>find('/wechat'),'wechat');let w=find('/wechat');await ready(w)
    const captures=path.join(__dirname,'../.artifacts/wechat-20260918');fs.mkdirSync(captures,{recursive:true})
    if(process.argv.includes('--restore-only')){
      await check('chat configuration, draft and guest address restore after process restart',async()=>{
        const s=await evaluate(w,'window.chatModeControl.get()');assert.equal(s.settings.orientation,'portrait');assert.equal(s.settings.scale,100)
        assert.equal(s.conversations.find(c=>c.id==='group').messages.at(-1).address,'https://www.douyin.com/video/123')
        assert.equal(s.drafts.lin,'保留草稿');assert.ok(s.conversations.find(c=>c.id==='group').messages.some(m=>m.text==='正式微信验收消息'))
        await until(()=>evaluate(w,'document.querySelector("webview")?.dataset.playerReady==="true"'),'restored guest')
        const g=webContents.fromId(await evaluate(w,'document.querySelector("webview").getWebContentsId()'));assert.equal(g.getURL(),'https://www.douyin.com/video/123')
      })
    }else{
      await check('approved seven-contact sparse UI and decoded source avatars replace full-panel webview',async()=>{
        assert.equal(await evaluate(w,'document.querySelectorAll(".chat-item").length'),7);assert.equal(await evaluate(w,'document.querySelectorAll("webview").length'),0)
        assert.equal(await evaluate(w,'Array.from(document.querySelectorAll("img.avatar")).every(i=>i.complete&&i.naturalWidth>0)'),true)
        assert.equal(await evaluate(w,'getComputedStyle(document.querySelector(".composer")).height'),'144px')
        await assert.rejects(evaluate(home,'window.chatModeControl.get()'),/微信窗口/)
      })
      w.showInactive();await pause(180);fs.writeFileSync(path.join(captures,'wechat-default.png'),(await w.webContents.capturePage()).toPNG())
      await check('local messages and IME Enter are safe and configuration persists',async()=>{
        await evaluate(w,`(()=>{const i=document.querySelector('textarea.message-input');i.value='正式微信验收消息';i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));})()`)
        await pause(120);assert.equal(await evaluate(w,'document.querySelectorAll("[data-conversation=group] .message-row").length'),3)
        await click(w,'send');await until(()=>evaluate(w,'document.querySelectorAll("[data-conversation=group] .message-row").length===4'),'sent')
        await evaluate(w,`(()=>{const i=document.querySelector('textarea.message-input');i.value='换行';i.dispatchEvent(new Event('input',{bubbles:true}));i.setSelectionRange(2,2);i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',ctrlKey:true,bubbles:true}));})()`)
        assert.equal(await evaluate(w,'document.querySelector("textarea.message-input").value'),'换行\n')
      })
      await click(w,'insert');await until(()=>evaluate(w,'document.querySelector("webview")?.dataset.playerReady==="true"'),'guest ready')
      const guest=webContents.fromId(await evaluate(w,'document.querySelector("webview").getWebContentsId()')),guestId=guest.id
      await check('folder inserts one real isolated guest which receives compact clicks and wheel',async()=>{
        assert.equal(await guest.executeJavaScript('typeof require'),'undefined');assert.equal(await guest.executeJavaScript('typeof window.chatModeControl'),'undefined')
        const b=await guest.executeJavaScript(`(()=>{const r=document.querySelector('[aria-label="下一条视频"]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`),zoom=guest.getZoomFactor()
        guest.sendInputEvent({type:'mouseDown',x:Math.round(b.x*zoom),y:Math.round(b.y*zoom),button:'left',clickCount:1});guest.sendInputEvent({type:'mouseUp',x:Math.round(b.x*zoom),y:Math.round(b.y*zoom),button:'left',clickCount:1})
        await until(()=>guest.executeJavaScript('document.body.dataset.next==="yes"'),'real compact click')
        guest.sendInputEvent({type:'mouseWheel',x:40,y:40,deltaY:100,deltaX:0});await until(()=>guest.executeJavaScript('document.body.dataset.wheel==="yes"'),'real wheel')
        await click(w,'insert');await pause(100);assert.equal(await evaluate(w,'document.querySelectorAll("webview").length'),1)
      })
      await check('asynchronously replaced site player gets viewport fit and inactive players stay untouched',async()=>{
        await guest.executeJavaScript(`(()=>{const old=document.querySelector('.xgplayer'),next=document.createElement('div');next.className='xgplayer';next.id='async-player';while(old.firstChild)next.appendChild(old.firstChild);old.replaceWith(next);const inactive=document.createElement('div');inactive.id='inactive';inactive.className='xgplayer';inactive.style.display='none';document.body.appendChild(inactive)})()`)
        await until(()=>guest.executeJavaScript('document.getElementById("async-player").hasAttribute("data-moyu-chat-active")'),'asynchronous player fit')
        assert.equal(await guest.executeJavaScript('getComputedStyle(document.getElementById("inactive")).position'),'relative')
      })
      await check('scale, portrait and interaction mask update in place without native window expansion',async()=>{
        const bounds=w.getBounds();await click(w,'more');await click(w,'settings');await input(w,'orientation','portrait');await input(w,'scale',100)
        await until(()=>evaluate(w,'document.querySelector(".chat-player").offsetWidth===160'),'portrait layout')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId);assert.deepEqual(w.getBounds(),bounds)
        await evaluate(w,`const i=document.querySelector('[data-setting=mask]');i.checked=true;i.dispatchEvent(new Event('change',{bubbles:true}))`)
        await until(()=>evaluate(w,'Boolean(document.querySelector(".player-mask"))'),'mask');await click(w,'close-dialog');await evaluate(w,'document.querySelector(".player-mask").click()')
        assert.equal(await evaluate(w,'Boolean(document.querySelector(".player-mask"))'),false)
      })
      await check('navigation keeps the guest and saves actual Douyin address',async()=>{
        await evaluate(w,`document.querySelector('webview').loadURL('https://www.douyin.com/video/123')`)
        await until(()=>guest.getURL()==='https://www.douyin.com/video/123','navigate');await until(async()=>{const s=await evaluate(w,'window.chatModeControl.get()');return s.conversations.find(c=>c.id==='group').messages.at(-1).address==='https://www.douyin.com/video/123'},'saved navigation')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId)
        await assert.rejects(evaluate(w,`(()=>{return window.chatModeControl.get().then(s=>{s.settings.address='javascript:alert(1)';return window.chatModeControl.save(s,s.revision)})})()`))
      })
      await check('boss covers video in visible chat and restores same guest and playing state',async()=>{
        await until(()=>guest.executeJavaScript('!document.querySelector("video").paused'),'playing')
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'Boolean(document.querySelector("[data-cover=chat-video]"))'),'boss cover')
        assert.ok(w.isVisible());assert.equal(w.getOpacity(),1);await until(()=>guest.executeJavaScript('document.querySelector("video").paused'),'boss paused')
        fs.writeFileSync(path.join(captures,'wechat-covered.png'),(await w.webContents.capturePage()).toPNG())
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'!document.querySelector("[data-cover=chat-video]")'),'boss restore')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId);await until(()=>guest.executeJavaScript('!document.querySelector("video").paused'),'restore playing')
      })
      await check('boss never starts a manually paused video or exposes newly autoplaying video',async()=>{
        await guest.executeJavaScript('document.querySelector("video").pause()')
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'Boolean(document.querySelector("[data-cover]"))'),'cover manually paused')
        await guest.executeJavaScript('document.querySelector("video").play()');await until(()=>guest.executeJavaScript('document.querySelector("video").paused'),'autoplay re-paused while covered')
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'!document.querySelector("[data-cover]")'),'restore autoplay test')
        await until(()=>guest.executeJavaScript('!window.__moyuChatPauseRequested&&!document.querySelector("video").paused'),'autoplay test actual media restored')
        await guest.executeJavaScript('document.querySelector("video").pause()')
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'Boolean(document.querySelector("[data-cover]"))'),'second cover')
        await until(()=>guest.executeJavaScript('window.__moyuChatPauseRequested===true'),'actual second cover paused')
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'!document.querySelector("[data-cover]")'),'second restore');await until(()=>guest.executeJavaScript('window.__moyuChatPauseRequested===false'),'actual second restore settled')
        assert.equal(await guest.executeJavaScript('document.querySelector("video").paused'),true)
        await guest.executeJavaScript('document.querySelector("video").play()')
      })
      await check('conversation switch preserves guest, pauses hidden media and retains drafts',async()=>{
        await evaluate(w,'document.querySelector("[data-chat=lin]").click()');await until(()=>guest.executeJavaScript('document.querySelector("video").paused'),'hidden paused')
        await evaluate(w,`const i=document.querySelector('textarea.message-input');i.value='保留草稿';i.dispatchEvent(new Event('input',{bubbles:true}))`)
        await until(async()=>{const s=await evaluate(w,'window.chatModeControl.get()');return s.drafts.lin==='保留草稿'},'draft saved')
        await evaluate(w,'document.querySelector("[data-chat=group]").click()');await until(()=>guest.executeJavaScript('!document.querySelector("video").paused'),'visible resumed')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId)
      })
      await check('invalid JSON retains chat and Escape dismisses more menu',async()=>{
        await click(w,'more');await click(w,'config');await evaluate(w,`const j=document.querySelector('.json-input');j.value='{bad';j.dispatchEvent(new Event('input',{bubbles:true}))`)
        const before=await evaluate(w,'window.chatModeControl.get()');await click(w,'apply-json');await until(()=>evaluate(w,'Boolean(document.querySelector(".config-error").textContent)'),'invalid JSON feedback');assert.deepEqual(await evaluate(w,'window.chatModeControl.get()'),before)
        await click(w,'close-dialog');await click(w,'more');await evaluate(w,'document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');assert.equal(await evaluate(w,'Boolean(document.querySelector(".wechat-more-menu"))'),false)
      })
      await check('structured configuration updates immediately and JSON address update reaches the same guest',async()=>{
        await click(w,'more');await click(w,'config')
        await evaluate(w,`(()=>{const i=document.querySelector('.contact-editor input');i.value='项目小组验收';i.dispatchEvent(new Event('input',{bubbles:true}))})()`)
        await click(w,'save-config');await until(()=>evaluate(w,'document.querySelector(".chat-title h2").textContent.includes("项目小组验收")'),'structured config applied')
        await evaluate(w,`(()=>{const j=document.querySelector('.json-input'),s=JSON.parse(j.value);s.conversations.find(c=>c.id==='group').messages.at(-1).address='https://www.douyin.com/video/789';j.value=JSON.stringify(s);j.dispatchEvent(new Event('input',{bubbles:true}))})()`)
        await click(w,'apply-json');await until(()=>guest.getURL()==='https://www.douyin.com/video/789','JSON address live sync')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId)
        await click(w,'close-dialog');await evaluate(w,`document.querySelector('webview').loadURL('https://www.douyin.com/video/123')`)
        await until(()=>guest.getURL()==='https://www.douyin.com/video/123','restore smoke URL')
      })
      await check('applying address in settings navigates exactly once without rebuilding guest',async()=>{
        await until(()=>evaluate(w,'document.querySelector("webview").dataset.playerReady==="true"'),'guest before address settings')
        let navigations=0;const listener=(_e,url,_inPlace,main)=>{if(main&&url==='https://www.douyin.com/video/456')navigations++};guest.on('did-start-navigation',listener)
        await click(w,'more');await click(w,'settings');await evaluate(w,`document.querySelector('[aria-label="抖音页面地址"]').value='https://www.douyin.com/video/456';document.querySelector('[aria-label="抖音页面地址"]').dispatchEvent(new Event('input',{bubbles:true}))`)
        await click(w,'apply-address');await until(()=>guest.getURL()==='https://www.douyin.com/video/456','address applied');await pause(100);guest.removeListener('did-start-navigation',listener)
        assert.equal(navigations,1);assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId)
        await click(w,'close-dialog');await evaluate(w,`document.querySelector('webview').loadURL('https://www.douyin.com/video/123')`)
        await until(()=>guest.getURL()==='https://www.douyin.com/video/123','restore test URL')
      })
      await check('foreign top-level redirects are denied before replacing current page or saved address',async()=>{
        await until(()=>evaluate(w,'document.querySelector("webview").dataset.playerReady==="true"'),'before redirect policy')
        let attempted=false;const seen=()=>{attempted=true};guest.once('will-redirect',seen)
        await guest.executeJavaScript(`location.href='https://www.douyin.com/redirect-block'`)
        await until(()=>attempted,'actual redirect');await pause(150)
        assert.equal(guest.getURL(),'https://www.douyin.com/video/123')
        assert.equal((await evaluate(w,'window.chatModeControl.get()')).settings.address,'https://www.douyin.com/video/123')
      })
      await check('allowed same-site redirect becomes the ready and persisted canonical address',async()=>{
        await evaluate(home,`window.chatModeControl.open('https://www.douyin.com/redirect-insite')`)
        await until(()=>guest.getURL()==='https://www.douyin.com/video/canonical','same-site canonical redirect')
        await until(async()=>{const s=await evaluate(w,'window.chatModeControl.get()');return s.settings.address==='https://www.douyin.com/video/canonical'},'canonical address saved')
        assert.equal(await evaluate(w,'document.querySelector("webview").dataset.playerReady'),'true')
        await evaluate(home,`window.chatModeControl.open('https://www.douyin.com/video/123')`);await until(()=>guest.getURL()==='https://www.douyin.com/video/123','restore redirect test URL')
      })
      await check('homepage mode entry preserves address unless explicit target is supplied',async()=>{
        await evaluate(home,'window.chatModeControl.open()');assert.equal((await evaluate(w,'window.chatModeControl.get()')).settings.address,'https://www.douyin.com/video/123')
        await evaluate(home,`window.chatModeControl.open('https://www.douyin.com/video/999')`);await until(()=>guest.getURL()==='https://www.douyin.com/video/999','homepage explicit target')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId)
        await evaluate(w,`document.querySelector('webview').loadURL('https://www.douyin.com/video/123')`);await until(()=>guest.getURL()==='https://www.douyin.com/video/123','restore entry test URL')
      })
      await check('address changed while guest is loading wins over the delayed old navigation',async()=>{
        await evaluate(home,`window.chatModeControl.open('https://www.douyin.com/video/slowA')`)
        await until(()=>evaluate(w,'document.querySelector("webview").dataset.playerReady==="false"'),'slow guest loading')
        await evaluate(home,`window.chatModeControl.open('https://www.douyin.com/video/fastB')`)
        await until(()=>guest.getURL()==='https://www.douyin.com/video/fastB','new address supersedes slow navigation');await pause(900)
        const saved=await evaluate(w,'window.chatModeControl.get()');assert.equal(saved.settings.address,'https://www.douyin.com/video/fastB')
        assert.equal(saved.conversations.find(c=>c.id==='group').messages.at(-1).address,'https://www.douyin.com/video/fastB');assert.equal(guest.getURL(),'https://www.douyin.com/video/fastB')
        assert.equal(await evaluate(w,'document.querySelector("webview").getWebContentsId()'),guestId)
        await evaluate(home,`window.chatModeControl.open('https://www.douyin.com/video/123')`);await until(()=>guest.getURL()==='https://www.douyin.com/video/123','restore delayed address test')
      })
      await check('mixed boss hides transparency but only covers chat',async()=>{
        await evaluate(home,'window.homeElectronAPI.createDouyinOpacity()');await until(()=>find('/douyinOpacity'),'transparent');const t=find('/douyinOpacity')
        await until(()=>evaluate(t,'Boolean(document.querySelector("[data-action=zoom]"))'),'transparent renderer ready')
        await until(()=>t.isVisible(),'transparent visible before boss')
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>t.getOpacity()===0,'transparent hidden');assert.equal(w.getOpacity(),1)
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>t.getOpacity()>0,'transparent restored');t.close()
      })
      fs.writeFileSync(path.join(captures,'wechat-player.png'),(await w.webContents.capturePage()).toPNG())
      await check('native close cleans guests and reopened window restores committed configuration',async()=>{
        await click(w,'close');await until(()=>!find('/wechat'),'closed');assert.ok(guest.isDestroyed())
        await evaluate(home,'window.homeElectronAPI.createWechat()');await until(()=>find('/wechat'),'reopened');w=find('/wechat');await ready(w)
        assert.equal((await evaluate(w,'window.chatModeControl.get()')).settings.scale,100)
      })
      await check('opening chat while boss is active inherits video cover without hiding window',async()=>{
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await click(w,'close');await until(()=>!find('/wechat'),'close covered chat')
        await evaluate(home,'window.homeElectronAPI.createWechat()');await until(()=>find('/wechat'),'reopen covered');w=find('/wechat');await ready(w)
        assert.ok(await evaluate(w,'Boolean(document.querySelector("[data-cover=chat-video]"))'));assert.ok(w.isVisible())
        await evaluate(home,"window.ipcRenderer.invoke('boss-key')");await until(()=>evaluate(w,'!document.querySelector("[data-cover]")'),'late chat restored')
      })
      await check('no renderer console errors',async()=>assert.deepEqual(errors,[]))
    }
    console.log('WECHAT_RESULT '+JSON.stringify({passed,failed:0,onlineDouyinVerified:false}));clearTimeout(watchdog);globalShortcut.unregisterAll();app.exit(0)
  }catch(e){console.error(e);console.error('RENDERER_ERRORS',errors);for(const w of BrowserWindow.getAllWindows())console.error('WINDOW',w.webContents.getURL(),await evaluate(w,'document.body.innerText').catch(()=>''));clearTimeout(watchdog);app.exit(1)}
})
require('../out/main/index.js')
