<template>
  <section v-if="state" class="dingtalk formal-dingtalk" :class="{'show-list':showList}" :data-chat-ready="true" @click="outside">
    <header class="top-bar"><div class="top-account"><span class="ding-logo">叶</span><span>{{state.selfName}}</span></div><label><ChatIcon name="search"/><input v-model="search" aria-label="全局搜索会话" placeholder="搜索"/></label><span>钉钉</span></header>
    <div class="client-body">
      <nav class="navigation"><button v-for="(n,i) in navs" :key="n" :class="{active:i===0}" @click="i?notice(n):showList=!showList"><span class="nav-glyph">{{navGlyphs[i]}}</span>{{n}}</button><span class="nav-space"/><button @click.stop="more=!more"><ChatIcon name="menu"/>更多</button></nav>
      <aside class="conversation-list"><div class="list-heading"><span>消息</span><button @click="openConfig"><ChatIcon name="plus"/></button></div><div class="chat-items"><button v-for="c in filtered" :key="c.id" class="chat-item" :class="{selected:c.id===state.selectedId}" :data-chat="c.id" @click="select(c.id)"><span class="avatar" :class="'tone-'+c.avatar">{{avatarText(c)}}</span><span class="chat-meta"><span><b>{{c.name}}</b><time>{{c.messages.at(-1)?.time}}</time></span><small>{{summary(c)}}</small></span><i v-if="c.unread">{{c.unread}}</i></button></div></aside>
      <main class="chat-panel"><header class="chat-header"><div class="chat-title"><button class="mobile-list" @click="showList=!showList"><ChatIcon name="menu"/></button><span class="avatar" :class="'tone-'+chat.avatar">{{avatarText(chat)}}</span><h2>{{chat.name}} <small v-if="chat.memberCount">({{chat.memberCount}})</small></h2></div><div class="header-actions"><button @click="notice('语音通话')">☎</button><button @click="notice('视频通话')">▣</button><button data-action="more" @click.stop="more=!more"><ChatIcon name="more"/></button><button data-action="close" @click="close"><ChatIcon name="close"/></button></div></header>
        <div v-if="more" class="more-menu" @click.stop><button data-action="settings" @click="openSettings">播放器设置</button><button data-action="config" @click="openConfig">聊天配置</button><button data-action="menu-insert" @click="insert">插入{{platformLabel}}播放器</button></div>
        <div class="all-messages"><section v-for="c in state.conversations" v-show="c.id === state.selectedId" :key="c.id" class="messages" :data-conversation="c.id"><div class="date-line">今天 · 本地演示时间</div><div v-for="m in c.messages" :key="m.id" class="message-row" :class="[m.sender,m.type+'-message']" :data-message="m.id"><span class="avatar" :class="'tone-'+(m.sender==='self'?'self':c.avatar)">{{m.sender==='self'?state.selfName[0]:(m.name||c.contact)[0]}}</span><div class="content-wrap"><span v-if="m.sender==='other'&&c.memberCount" class="sender-name">{{m.name||c.contact}}</span><ChatPlayer v-if="m.type==='player'" :platform="platform.platform" :label="platform.definition.label" :partition="platform.partition" :message="m" :settings="state.settings" :covered="covered" :active="c.id===state.selectedId" @navigate="address=>saveNavigation(c.id,m.id,address)" @error="message=>error=message"/><div v-else class="bubble">{{m.text}}</div><span v-if="m.sender==='self'" class="read-state">已读</span></div></div></section></div>
        <footer class="composer"><div class="composer-tools"><button title="表情"><ChatIcon name="smile"/></button><button data-action="insert" :title="'插入'+platformLabel+'播放器'" @click="insert"><ChatIcon name="folder"/></button><button title="收藏"><ChatIcon name="cube"/></button><button title="截屏"><ChatIcon name="cut"/></button><span/><button title="播放器设置" @click="openSettings">⚙</button><button title="聊天配置" @click="openConfig">♙</button></div><textarea class="message-input" :value="draft" aria-label="输入本地消息" maxlength="2000" @input="draftInput" @keydown="keydown"/><div class="composer-bottom"><span>Enter 发送，Shift+Enter 换行</span><button data-action="send" :disabled="!draft.trim()" @click="send">发送</button></div></footer>
      </main>
    </div>
    <div v-if="error" class="chat-notice" role="alert">{{error}}<button @click="error=''">×</button></div>
    <div v-if="dialog" class="dialog-scrim" @click.self="dialog=''"> <section class="chat-dialog" role="dialog" aria-modal="true"><header><h3>{{dialog==='settings'?'播放器设置':'聊天配置'}}</h3><button data-action="close-dialog" @click="dialog=''">×</button></header>
      <div v-if="dialog==='settings'" class="dialog-body"><label>{{platformLabel}}地址<input v-model="addressInput" :aria-label="platformLabel+'页面地址'"/></label><button data-action="apply-address" @click="applyAddress">应用到当前播放器</button><label>方向<select data-setting="orientation" :value="state.settings.orientation" @change="setting('orientation',$event.target.value)"><option value="landscape">横屏</option><option value="portrait">竖屏</option></select></label><label>大小 {{state.settings.scale}}%<input data-setting="scale" type="range" min="80" max="200" step="10" :value="state.settings.scale" @change="setting('scale',Number($event.target.value))"/></label><label>发送方<select data-setting="sender" :value="state.settings.sender" @change="setting('sender',$event.target.value)"><option value="self">自己</option><option value="other">对方</option></select></label><label><input data-setting="mask" type="checkbox" :checked="state.settings.mask" @change="setting('mask',$event.target.checked)"/>交互遮罩</label></div>
      <div v-else class="dialog-body"><label>自己的昵称<input v-model="editConfig.selfName"/></label><label>会话<select v-model="editId"><option v-for="c in editConfig.conversations" :key="c.id" :value="c.id">{{c.name}}</option></select></label><template v-if="editChat"><label>会话名称<input v-model="editChat.name"/></label><label>联系人<input v-model="editChat.contact"/></label><label>成员数<input v-model.number="editChat.memberCount" type="number" min="0" max="999"/></label><label>头像<select v-model="editChat.avatar"><option v-for="a in avatars" :key="a">{{a}}</option></select></label></template><button data-action="save-config" @click="replace(editConfig)">保存编辑</button><label>JSON 导入/导出<textarea class="json-input" v-model="jsonInput"/></label><p class="config-error">{{configError}}</p><button data-action="apply-json" @click="applyJson">应用 JSON</button><button data-action="reset" @click="replace(createChatState('dingtalk',platform.platform))">恢复默认</button></div>
    </section></div>
  </section><div v-else class="formal-dingtalk chat-startup">{{error||'正在加载钉钉模式…'}}<button v-if="error" @click="load">重试</button></div>
</template>
<script setup>
import {ref,computed,onMounted,onBeforeUnmount,watch,nextTick} from 'vue'
import ChatIcon from '../features/chat/ChatIcon.vue';import ChatPlayer from '../features/chat/ChatPlayer.vue';import {createChatController,loadChatRuntime} from '../features/chat/controller.mjs';import {loadChatPlatform} from '../features/chat/platform-runtime.mjs';import {createChatState,currentChat,sendText,insertPlayer,validateChatState,validateChatUrl} from '../../../shared/chat-state.mjs';import '../features/chat/dingtalk.css'
const navs=['消息','DING','文档','日历','工作台','通讯录'],navGlyphs=['▣','✓','▤','▦','▢','♙'],avatars=['blue','green','purple','orange','file','self']
const state=ref(null),platform=ref(null),covered=ref(false),search=ref(''),draft=ref(''),error=ref(''),more=ref(false),dialog=ref(''),showList=ref(false),addressInput=ref(''),editConfig=ref(null),editId=ref(''),jsonInput=ref(''),configError=ref('');const api=window.videoChatModeControl,unsubs=[];let disposed=false,bossRevision=0
const platformLabel=computed(()=>platform.value?.definition.label||'视频')
const controller=createChatController({api,validate:raw=>validateChatState(raw,'dingtalk',platform.value?.platform||raw?.settings?.site||'douyin'),onState:s=>state.value=s,onError:e=>error.value=e.message});const chat=computed(()=>state.value?currentChat(state.value):null),filtered=computed(()=>state.value?.conversations.filter(c=>c.name.toLowerCase().includes(search.value.trim().toLowerCase()))||[]),editChat=computed(()=>editConfig.value?.conversations.find(c=>c.id===editId.value))
const avatarText=c=>c.memberCount?'组':c.name[0],summary=c=>{const m=c.messages.at(-1);return !m?'':m.type==='player'?`[${platformLabel.value}视频]`:(m.sender==='self'?'我：':'')+m.text};const update=fn=>controller.update(fn).catch(()=>null)
function notice(n){error.value=n+'仅保留钉钉外观，未连接真实钉钉。'}function outside(e){if(!e.target.closest('[data-action=more],.more-menu'))more.value=false}function draftInput(e){draft.value=e.target.value;const id=state.value.selectedId,value=draft.value;update(s=>s.drafts[id]=value)}
function select(id){const old=state.value.selectedId,value=draft.value;showList.value=false;update(s=>{s.drafts[old]=value;s.selectedId=id;s.conversations.find(c=>c.id===id).unread=0})}async function scroll(id){await nextTick();const n=document.querySelector(`[data-conversation="${id}"]`);if(n)n.scrollTop=n.scrollHeight}
async function send(){const value=draft.value,id=state.value.selectedId;if(!value.trim())return;const ok=await update(s=>{const selected=s.selectedId;s.selectedId=id;sendText(s,value);s.selectedId=selected;s.drafts[id]=''});if(ok&&state.value.selectedId===id&&draft.value===value)draft.value='';if(ok)scroll(id)}
function keydown(e){if(e.key!=='Enter'||e.isComposing||e.keyCode===229)return;if(e.shiftKey||e.ctrlKey)return;e.preventDefault();send()}async function insert(){more.value=false;dialog.value='';const id=state.value.selectedId,exists=chat.value.messages.some(m=>m.type==='player'),ok=await update(s=>insertPlayer(s));if(ok){if(exists)error.value=`此会话已有${platformLabel.value}播放器。`;scroll(id)}}
function setting(k,v){update(s=>s.settings[k]=v)}function saveNavigation(cid,mid,address){const old=state.value.conversations.find(c=>c.id===cid)?.messages.find(m=>m.id===mid);if(!old||old.address===address)return;update(s=>{const m=s.conversations.find(c=>c.id===cid)?.messages.find(m=>m.id===mid);if(m)m.address=address;s.settings.address=address})}
async function applyAddress(){try{const address=validateChatUrl(addressInput.value,platform.value.platform),id=state.value.selectedId;await update(s=>{s.settings.address=address;const m=s.conversations.find(c=>c.id===id).messages.find(m=>m.type==='player');if(m)m.address=address})}catch(e){error.value=e.message}}function openSettings(){more.value=false;addressInput.value=state.value.settings.address;dialog.value='settings'}function openConfig(){more.value=false;editConfig.value=validateChatState(state.value,'dingtalk',platform.value.platform);editId.value=state.value.selectedId;jsonInput.value=JSON.stringify(state.value,null,2);configError.value='';dialog.value='config'}
async function replace(raw){try{const candidate=validateChatState(raw,'dingtalk',platform.value.platform),saved=await controller.update(s=>{const revision=s.revision;Object.assign(s,candidate,{revision})});editConfig.value=structuredClone(saved);jsonInput.value=JSON.stringify(saved,null,2);configError.value=''}catch(e){configError.value=e.message}}function applyJson(){try{return replace(JSON.parse(jsonInput.value))}catch(e){configError.value='JSON 格式错误：'+e.message}}async function close(){try{await api.close()}catch(e){error.value=e.message}}
async function load(){error.value='';try{platform.value=await loadChatPlatform(api,'dingtalk');const rev=bossRevision;await loadChatRuntime(controller,api,r=>{if(!disposed&&rev===bossRevision)covered.value=r.covered;if(r.warning)error.value=r.warning});draft.value=state.value.drafts[state.value.selectedId]||'';scroll(state.value.selectedId)}catch(e){error.value=e.message}}
watch(()=>state.value?.selectedId,id=>{if(id){draft.value=state.value.drafts[id]||'';scroll(id)}});onMounted(()=>{unsubs.push(api.onState(s=>controller.accept(s)),api.onBoss(v=>{bossRevision++;covered.value=v}),api.onError(m=>error.value=m));load()});onBeforeUnmount(()=>{disposed=true;controller.dispose();unsubs.forEach(f=>f())})
</script>
